//try...catch errors are generated by JavaScript's Error object class

//You can also throw or 'raise' errors yourself, which initiates an 'exception'

//Unlike other languages with Exception Handling, you can throw any value
//that is a number or a string. It is, however, convention to use an instance of Error
//if you don't use error, consider that functions you create to catch exceptions
//may well be used by other programmers who expect instances of Error.
//when you call throw, the current function immediately stops executing.

class Account {
    constructor(name, balance) {
        this.name = name;
        this.balance = balance;
    }
    transfer(payee, amount) {
    this.balance = this.balance - amount;
    payee.balance = payee.balance + amount;
    }
}

var jeff = new Account('Jeff', 100);
var sophia = new Account('Sophia', 50);

//author's example for error, everything else is mine!
function billPay(amount, payee, account) {
    if(amount > account.balance)
        throw new Error("Insufficient Funds!");
    account.transfer(payee, amount);
}

console.log(sophia.balance);
console.log(jeff.balance);
billPay(50, jeff, sophia);
console.log(sophia.balance);
console.log(jeff.balance);
//oh my god this stuff is actually occupying my brain.
